services:
  - type: web
    name: chatroom-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npx tsc
    startCommand: node dist/index.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_yKiXY6e1bJsC@ep-frosty-glade-ahqza772.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: "*"
      - key: NODE_ENV
        value: production
